# Neural Collaborative Filtering Model Configuration
#
# Combines GMF (Generalized Matrix Factorization) and MLP
# for learning user-item interactions.
# Reference: He et al., "Neural Collaborative Filtering" (WWW 2017)

model:
  name: ncf
  class: NeuralCollaborativeFiltering
  module: app.models.ncf
  description: "Neural CF combining GMF and MLP paths"

architecture:
  gmf_embedding_dim: 32
  mlp_embedding_dim: 32
  mlp_layers: [64, 32, 16]
  dropout: 0.1

training:
  optimizer: adam
  learning_rate: 0.001
  weight_decay: 0.0001
  batch_size: 256
  epochs: 15
  loss: bce_with_logits
  train_split: 0.8
  early_stopping:
    enabled: true
    patience: 5
    min_delta: 0.001

evaluation:
  metrics:
    - auc
    - precision
    - recall
    - ndcg@10
    - hit_rate@10

features:
  user_features: []
  item_features: []
